### ISSUE TITLE
Visualization of output file

### ISSUE THREAD

**Issue by alien19** [pahn04/PPConv#2]
Thanks for mentioning [here ](https://github.com/pahn04/PPConv/issues/1#issuecomment-1110873413_)that FPConv provided a code for visualization of the output .npy files. But in the case of PVCNN (after running the test_s3dis.bash script which call train.py with --evaluate flag) just one .npy file is written "xxxx.eval.npy".
Also when I try to run eval.py in evaluate/s3dis it gives **Segmentation fault**

**Comment by pahn04** [comment]
Hi.

For visualization, you will need to run test using fpconv_code. The file named "best.eval.npy" that you got from pvcnn_code only contains the statistical information of the prediction, not the prediction itself. Thus, you could modify the evaluation code to save predictions of all points into a .npy file for each scene, or use the fpconv_code instead.
